kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mw-aks-azure-fileshare
provisioner: file.csi.azure.com
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: Standard_ZRS