kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysql-deployment
  labels:
    name: mysql-deployment
    app: mysql-aks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
      app: mysql-aks-deployment
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod
        app: mysql-aks-deployment
    spec:
      containers:
        - name: mysql-container
          image: mysql:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
  #          - mountPath: /docker-entrypoint-initdb.d
  #            name: mysql-initdb
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
#        - name: mysql-initdb
#          configMap:
#            name: mysql-configmap
          