apiVersion: v1
kind: Service
metadata:
  name: mwiki-service
  labels:
    name: mwiki-service
    app: mwiki-aks-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: mediawiki-pod
  