apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    name: mysql-data-store
    app: mysql-aks-deployment
data:
  MYSQL_DATABASE: #put your database name to be used for Mediawiki
  MYSQL_USER: #put the db user name for the above database