kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Release.Name }}-mysql-deployment
  labels:
    name: {{ .Release.Name }}-mysql-deployment
    app: {{ .Release.Name }}-mysql-aks-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}-mysql-pod
      app: {{ .Release.Name }}-mysql-aks-deployment
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-mysql-pod
        app: {{ .Release.Name }}-mysql-aks-deployment
    spec:
      containers:
        - name: {{ .Release.Name }}-mysql-container
          image: {{ .Values.image.repository }}:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mysql-pvc
          