apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    name: mysql-secret
    app: mysql-aks-deployment
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdHVzZXIxMjM=
  MYSQL_PASSWORD: d2lraXVzZXIxMjM=