apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    name: mysql-secret
    app: mysql-aks-deployment
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: #put your base64 encoded password for root user of MySQL (can integrated secret management solutions)
  MYSQL_PASSWORD: #put your base64 encoded password for the db user created for mediawiki app (can integrated secret management solutions)