replicaCount: 1

image:
  repository: mediawiki
  pullPolicy: IfNotPresent


service:
  type: LoadBalancer
  port: 80

resources: 
  limits:
    cpu: 1.5
    memory: 1Gi
  requests:
    cpu: 1
    memory: 512Mi