replicaCount: 1

image:
  repository: mysql
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

resources:
  limits:
    cpu: 1.5
    memory: 1Gi
  requests:
    cpu: 1
    memory: 512Mi