apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mwiki-service
  labels:
    name: {{ .Release.Name }}-mwiki-service
    app: {{ .Release.Name }}-mwiki-aks-deployment
spec:
  type: {{ .Values.service.type}}
  ports:
  - port: {{ .Values.service.port}}
    targetPort: {{ .Values.service.port}}
  selector:
    name: {{ .Release.Name }}-mediawiki-pod
  